import { activeWorkspace, newWorkspace, saveWorkspace, selectWorkspace, deleteWorkspace, loadRoot } from "./store.js";
import { interpret } from "./parser.js";
import { plan, markBlockDone, applyProgress, cleanup } from "./planner.js";

const app=document.querySelector("#app"); let tab="today";
const esc=s=>String(s||"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const today=()=>localDate(new Date()); const pretty=d=>new Date(`${d}T12:00`).toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"}); const minutes=n=>n<60?`${n}m`:`${Math.floor(n/60)}h${n%60?` ${n%60}m`:""}`;
const current=()=>activeWorkspace().workspace;
function save(w){cleanup(w);plan(w);saveWorkspace(w);render();}
function boot(){const w=current();if(w){plan(w);saveWorkspace(w);render();}else welcome();}
function welcome(){app.innerHTML=`<section class="onboard"><div class="sun">◒</div><p class="eyebrow">DAYLIGHT</p><h1>Your time, already handled.</h1><p>A private, calm planner for your real week—not another calendar to maintain.</p><form id="start"><label>Your name or workspace<input autofocus required maxlength="50" placeholder="e.g. Abhinav" name="name"></label><button>Set up my planner →</button></form><small>Default study, meal, free-time and recovery rules are ready. You can edit all of them in Settings. Everything stays in this browser on this device.</small></section>`;document.querySelector("#start").onsubmit=e=>{e.preventDefault();saveWorkspace(newWorkspace(new FormData(e.target).get("name")));boot();};}
const commitments=(w,d)=>w.commitments.filter(c=>c.date===d).sort((a,b)=>a.start.localeCompare(b.start));
function todayView(w){const date=today(), planRows=w.plan.filter(b=>b.date===date), rows=[...planRows,...commitments(w,date).map(c=>({...c,kind:"fixed"}))].sort((a,b)=>a.start.localeCompare(b.start)), work=planRows.filter(b=>b.taskId).reduce((n,b)=>n+b.minutes,0);return `<section class="view"><div class="heading"><div><p class="eyebrow">${pretty(date)}</p><h1>Good ${new Date().getHours()<12?"morning":new Date().getHours()<18?"afternoon":"evening"}, ${esc(w.name)}.</h1><p class="sub">${work?`${minutes(work)} of purposeful work; free time is protected.`:"A lighter day is available. Tell me what matters and I’ll fit it in."}</p></div><button class="outline" data-action="replan">↻ Replan</button></div>${w.prompts.length?`<div class="prompts">${w.prompts.map(p=>`<article class="prompt ${p.level}"><b>${p.level==="ask"?"Approval needed":p.level==="prompt"?"Heads up":"Plan update"}</b><span>${esc(p.text)}</span></article>`).join("")}</div>`:""}<div class="schedule">${rows.length?rows.map(x=>`<article class="block ${x.kind}"><time>${x.start}–${x.end}</time><div><b>${esc(x.title)}</b><small>${x.kind==="fixed"?"Hard commitment · read-only":x.kind==="dinner"?"Flexible meal window":`${esc(x.category)} · ${minutes(x.minutes)}`}</small></div>${x.taskId?`<button class="done" data-done="${x.id}">Done</button>`:""}</article>`).join(""):`<div class="empty">Nothing fixed here yet. Your evening is protected free time unless you add something important.</div>`}</div></section>`;}
function weekView(w){const now=new Date(),days=Array.from({length:7},(_,i)=>localDate(new Date(now.getFullYear(),now.getMonth(),now.getDate()+i)));return `<section class="view"><div class="heading"><div><p class="eyebrow">NEXT 7 DAYS</p><h1>Your week</h1><p class="sub">Work is placed where it helps; recovery and unstructured time remain visible.</p></div><button class="outline" data-action="replan">↻ Replan</button></div><div class="week">${days.map(d=>{const items=[...commitments(w,d),...w.plan.filter(b=>b.date===d)].sort((a,b)=>a.start.localeCompare(b.start)),work=items.filter(x=>x.taskId).reduce((n,x)=>n+x.minutes,0);return `<article class="day"><header><b>${new Date(`${d}T12:00`).toLocaleDateString(undefined,{weekday:"short"})}</b><span>${new Date(`${d}T12:00`).getDate()}</span><small>${work?minutes(work):d===today()?"Open":"Recovery / free"}</small></header>${items.length?items.map(i=>`<div class="mini ${i.hard?"fixed":""}"><time>${i.start}</time>${esc(i.title)}</div>`).join(""):`<div class="mini free">Protected free time</div>`}</article>`;}).join("")}</div></section>`;}
function settingInput(label,name,type,value,extra=""){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function settingsView(w){const p=w.preferences,root=loadRoot();return `<section class="view settings"><p class="eyebrow">PRIVATE WORKSPACE</p><h1>Settings</h1><article class="card"><h2>Your weekly defaults</h2><form id="prefs">${settingInput("Wake", "wake", "time", p.wake)}${settingInput("Sleep", "sleep", "time", p.sleep)}${settingInput("Normal lecture start", "lectureStart", "time", p.lectureStart)}${settingInput("Normal lecture end", "lectureEnd", "time", p.lectureEnd)}${settingInput("Lunch start", "lunchStart", "time", p.lunchStart)}${settingInput("Lunch end", "lunchEnd", "time", p.lunchEnd)}${settingInput("Dinner window start", "dinnerStart", "time", p.dinnerStart)}${settingInput("Dinner window end", "dinnerEnd", "time", p.dinnerEnd)}${settingInput("Dinner minutes", "dinnerMinutes", "number", p.dinnerMinutes, "min=20 max=120 step=5")}${settingInput("Protected free time (minutes)", "protectedFreeMinutes", "number", p.protectedFreeMinutes, "min=30 max=360 step=30")}${settingInput("Saturday protected from", "saturdayFreeAfter", "time", p.saturdayFreeAfter)}<label class="check"><input name="lecturesEnabled" type="checkbox" ${p.lecturesEnabled?"checked":""}> Use normal weekday lectures</label><label class="check"><input name="sundayRecovery" type="checkbox" ${p.sundayRecovery?"checked":""}> Keep Sunday mostly free/recovery</label><button>Save preferences</button></form></article><article class="card"><h2>Private workspaces</h2><p>Workspaces never share planner data. For person-to-person privacy, each person should use their own phone/browser profile.</p><div class="workspace-list">${root.workspaces.map(x=>`<button data-workspace="${x.id}" class="${x.id===w.id?"selected":""}">${esc(x.name)}</button>${root.workspaces.length>1?`<button data-delete="${x.id}" class="danger">Delete</button>`:""}`).join("")}</div><button class="outline" data-action="new-workspace">Create another private workspace</button></article><article class="card"><h2>Known iPhone limit</h2><p>Daylight replans on launch and whenever something changes. A closed iPhone web app cannot reliably wake itself for a Monday notification without a hosted push service, so the weekly briefing appears on your next open.</p></article></section>`;}
function render(){const w=current();if(!w)return welcome();const view=tab==="today"?todayView(w):tab==="week"?weekView(w):tab==="tasks"?tasksView(w):settingsView(w);app.innerHTML=`<header class="top"><span class="brand">◒ Daylight</span><button class="avatar" data-tab="settings">${esc(w.name[0].toUpperCase())}</button></header>${view}<form class="capture" id="capture"><input name="input" autocomplete="off" placeholder="Tell me something… e.g. “SCOP meeting tomorrow at 7”"><button aria-label="Add">↑</button></form><nav>${[["today","Today"],["week","Week"],["tasks","Tasks"]].map(([k,n])=>`<button data-tab="${k}" class="${tab===k?"active":""}">${n}</button>`).join("")}</nav>`;bind();}
function findTask(w,query){return w.tasks.find(t=>t.status==="open"&&(t.title.toLowerCase().includes(query)||query.includes(t.title.toLowerCase())));}
function bind(){document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});document.querySelector("#capture")?.addEventListener("submit",e=>{e.preventDefault();const text=new FormData(e.target).get("input").trim();if(!text)return;const w=current(),r=interpret(text,new Date(),w.estimates);if(r.type==="task")w.tasks.push(r.value);else if(r.type==="commitment")w.commitments.push(r.value);else if(r.type==="recovery")w.recovery={...w.recovery,...r.value};else if(r.type==="progress"&&!applyProgress(w,r.value.query,r.value.amount))r.notes.push("I couldn’t tell which task that progress belongs to. Open Tasks and mark it complete, or mention its name.");else if(r.type==="completeByText"){const t=findTask(w,r.value);if(t){t.status="done";t.remainingMinutes=0;t.completedAt=new Date().toISOString();}else r.notes.push("I couldn’t find that open task.");}if(r.notes.length)w.prompts=r.notes.map((text,i)=>({id:`note-${Date.now()}-${i}`,level:"inform",text}));save(w);});document.querySelectorAll("[data-action='replan']").forEach(b=>b.onclick=()=>save(current()));document.querySelectorAll("[data-done]").forEach(b=>b.onclick=()=>save(markBlockDone(current(),b.dataset.done)));document.querySelectorAll("[data-complete]").forEach(b=>b.onclick=()=>{const w=current(),t=w.tasks.find(x=>x.id===b.dataset.complete);t.status="done";t.remainingMinutes=0;t.completedAt=new Date().toISOString();save(w);});document.querySelector("#prefs")?.addEventListener("submit",e=>{e.preventDefault();const w=current(),f=new FormData(e.target);Object.assign(w.preferences,Object.fromEntries(f));w.preferences.lecturesEnabled=f.has("lecturesEnabled");w.preferences.sundayRecovery=f.has("sundayRecovery");["protectedFreeMinutes","dinnerMinutes"].forEach(k=>w.preferences[k]=Number(w.preferences[k]));save(w);});document.querySelectorAll("[data-workspace]").forEach(b=>b.onclick=()=>{selectWorkspace(b.dataset.workspace);tab="today";boot();});document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{if(confirm("Delete this private workspace from this device?")){deleteWorkspace(b.dataset.delete);boot();}});document.querySelector("[data-action='new-workspace']")?.addEventListener("click",()=>{const name=prompt("Name for the new private workspace:");if(name){saveWorkspace(newWorkspace(name));boot();}});}
if("serviceWorker" in navigator){const worker=new URL("../service-worker.js",import.meta.url);const scope=new URL("../",import.meta.url);navigator.serviceWorker.register(worker,{scope:scope.pathname});}boot();
